Label modal
DukeAML/daml-dashboard pull request #12
Opened 2022-02-03 18:51 UTC by jamesw6688

deleted "upload data" option for text box; finalized the style modal for text box

2022-02-04 00:05 UTC, nfried16 commented on src/api/api.js
> +	//baseURL: "https://peagle-backend.herokuapp.com"
use this link

2022-02-07 17:15 UTC, nfried16 commented on src/components/dashboards/Grid.jsx
> +                        // padding: "1rem",
this is what caused the issue. Why did you do this??

2022-02-07 17:16 UTC, nfried16 commented on src/components/dashboards/Chart.jsx
> -                    x
you deleted the delete button, we need this!

2022-02-07 17:16 UTC, nfried16 commented on src/components/dashboards/Dashboards.css
>  }
I don't think these are ever used, so delete them

2022-02-07 17:18 UTC, nfried16 commented on src/components/widgetSelection/WidgetDataEntry.jsx
> +		console.log("check!")
delete these logs

2022-02-07 17:20 UTC, nfried16 commented on src/components/dashboards/DraftWidgetModal.jsx
> +    console.log(font, align, bold)
delete this

2022-02-07 17:20 UTC, nfried16 requested changes
make changes in comments

2022-02-10 22:36 UTC, jamesw6688 commented on src/components/dashboards/Dashboards.css
>  }
They are for the style of the text box modal. I think we need them

2022-02-10 23:35 UTC, closed without merging